### ISSUE TITLE
Spec failures for models with BelongsTo relationships

### ISSUE THREAD

**Issue by ELepolt** [thoughtbot/administrate#1976]
* What were you trying to do?
Many tests started failing after upgrading to 0.15.0. This particular admin page doesn't have anything overwriting it, and it appears to be occurring in others when there is a relationship

* What did you end up with (logs, or, even better, example apps are great!)?

It looks like this style of line of code is the culprit. What should this look like instead?

`quote_report_form: Field::BelongsTo.with_options(class_name: 'TestReportForm', order: :name)`

```
 ActionView::Template::Error:
       undefined method `constantize' for #<Class:0x00007fdc48c470a8>
       Did you mean?  constants
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/attr_encrypted-3.1.0/lib/attr_encrypted.rb:306:in `method_missing'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/attr_encrypted-3.1.0/lib/attr_encrypted/adapters/active_record.rb:131:in `method_missing_with_attr_encrypted'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/administrate-0.16.0/lib/administrate/field/associative.rb:28:in `associated_class'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/administrate-0.16.0/lib/administrate/field/has_one.rb:51:in `resolver'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/administrate-0.16.0/lib/administrate/field/has_one.rb:31:in `nested_form'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/administrate-0.16.0/app/views/fields/has_one/_form.html.erb:21:in `block in ___sers_evanlepolt__rvm_gems_ruby_______gems_administrate________app_views_fields_has_one__form_html_erb__174582463195192081_70292147536300'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/administrate-0.16.0/app/views/fields/has_one/_form.html.erb:19:in `___sers_evanlepolt__rvm_gems_ruby_______gems_administrate________app_views_fields_has_one__form_html_erb__174582463195192081_70292147536300'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/administrate-0.16.0/app/helpers/administrate/application_helper.rb:16:in `render_field'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/administrate-0.16.0/app/views/administrate/application/_form.html.erb:38:in `block (2 levels) in ___sers_evanlepolt__rvm_gems_ruby_______gems_administrate________app_views_administrate_application__form_html_erb___4207677310053208773_70292147700780'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/administrate-0.16.0/app/views/administrate/application/_form.html.erb:36:in `each'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/administrate-0.16.0/app/views/administrate/application/_form.html.erb:36:in `block in ___sers_evanlepolt__rvm_gems_ruby_______gems_administrate________app_views_administrate_application__form_html_erb___4207677310053208773_70292147700780'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/administrate-0.16.0/app/views/administrate/application/_form.html.erb:17:in `___sers_evanlepolt__rvm_gems_ruby_______gems_administrate________app_views_administrate_application__form_html_erb___4207677310053208773_70292147700780'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/administrate-0.16.0/app/views/administrate/application/edit.html.erb:35:in `___sers_evanlepolt__rvm_gems_ruby_______gems_administrate________app_views_administrate_application_edit_html_erb___1241800929566114609_70292011307760'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/wicked_pdf-1.2.2/lib/wicked_pdf/pdf_helper.rb:46:in `call'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/wicked_pdf-1.2.2/lib/wicked_pdf/pdf_helper.rb:46:in `render_with_wicked_pdf'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/wicked_pdf-1.2.2/lib/wicked_pdf/pdf_helper.rb:30:in `render'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/administrate-0.16.0/app/controllers/administrate/application_controller.rb:40:in `edit'
     # ./app/controllers/admin/application_controller.rb:34:in `set_time_zone'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/sentry-raven-2.13.0/lib/raven/integrations/rails/controller_transaction.rb:7:in `block in included'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192:in `call!'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/rack-tracker-1.12.1/lib/rack/tracker.rb:45:in `_call'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/rack-tracker-1.12.1/lib/rack/tracker.rb:41:in `call'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/rack-2.2.3/lib/rack/deflater.rb:44:in `call'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/rack-2.2.3/lib/rack/conditional_get.rb:27:in `call'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/chewy-5.0.0/lib/chewy/railtie.rb:19:in `block in call'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/chewy-5.0.0/lib/chewy/strategy.rb:70:in `wrap'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/chewy-5.0.0/lib/chewy.rb:201:in `strategy'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/chewy-5.0.0/lib/chewy/railtie.rb:19:in `call'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/railties-6.0.3.7/lib/rails/rack/logger.rb:37:in `call_app'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/railties-6.0.3.7/lib/rails/rack/logger.rb:26:in `block in call'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/railties-6.0.3.7/lib/rails/rack/logger.rb:26:in `call'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/ahoy_matey-2.2.1/lib/ahoy/engine.rb:20:in `call_with_quiet_ahoy'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/sentry-raven-2.13.0/lib/raven/integrations/rack.rb:51:in `call'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/rack-mini-profiler-2.0.1/lib/mini_profiler/profiler.rb:200:in `call'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/rack-cors-1.1.1/lib/rack/cors.rb:100:in `call'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/railties-6.0.3.7/lib/rails/engine.rb:527:in `call'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `each'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/rack-test-1.1.0/lib/rack/mock_session.rb:29:in `request'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/rack-test-1.1.0/lib/rack/test.rb:266:in `process_request'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/rack-test-1.1.0/lib/rack/test.rb:129:in `custom_request'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/rack-test-1.1.0/lib/rack/test.rb:58:in `get'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/capybara-2.18.0/lib/capybara/rack_test/browser.rb:69:in `process'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/capybara-2.18.0/lib/capybara/rack_test/browser.rb:41:in `process_and_follow_redirects'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/capybara-2.18.0/lib/capybara/rack_test/browser.rb:37:in `follow'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/capybara-2.18.0/lib/capybara/rack_test/node.rb:60:in `click'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/capybara-2.18.0/lib/capybara/node/element.rb:143:in `block in click'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/capybara-2.18.0/lib/capybara/node/base.rb:85:in `synchronize'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/capybara-2.18.0/lib/capybara/node/element.rb:143:in `click'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/capybara-2.18.0/lib/capybara/node/actions.rb:43:in `click_link'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/capybara-2.18.0/lib/capybara/session.rb:808:in `block (2 levels) in <class:Session>'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/capybara-2.18.0/lib/capybara/dsl.rb:50:in `block (2 levels) in <module:DSL>'
     # ./spec/features/admin/admin_walkthrough_spec.rb:71:in `block (4 levels) in <top (required)>'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/capybara-2.18.0/lib/capybara/session.rb:341:in `within'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/capybara-2.18.0/lib/capybara/dsl.rb:50:in `block (2 levels) in <module:DSL>'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/capybara-2.18.0/lib/capybara/rspec/matcher_proxies.rb:14:in `within'
     # ./spec/features/admin/admin_walkthrough_spec.rb:68:in `block (3 levels) in <top (required)>'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/rspec-retry-0.5.7/lib/rspec/retry.rb:115:in `block in run'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/rspec-retry-0.5.7/lib/rspec/retry.rb:104:in `loop'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/rspec-retry-0.5.7/lib/rspec/retry.rb:104:in `run'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/rspec-retry-0.5.7/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/rspec-retry-0.5.7/lib/rspec/retry.rb:33:in `block (2 levels) in setup'
     # ------------------
     # --- Caused by: ---
     # NoMethodError:
     #   undefined method `constantize' for #<Class:0x00007fdc48c470a8>
     #   Did you mean?  constants
     #   /Users/evanlepolt/.rvm/gems/ruby-2.5.3/gems/attr_encrypted-3.1.0/lib/attr_encrypted.rb:306:in `method_missing'
```

* What versions are you running?
  - Rails: 6.0.3.6
  - administrate: 0.15.0

**Comment by ELepolt** [comment]
My apologies. This was entirely my own fault, as we were using an actual class instead of string form of the class, and removing class_name altogether fixed it anyway.
