### ISSUE TITLE
Upgrade to v1 breaks with applications using Bootstrap 4.6

### ISSUE THREAD

**Issue by nickcharlton** [thoughtbot/administrate#2522]
Upgrade from 0.19 to v1 beta causes the following errors on pages that use custom modifications in view templates:

```
ActionView::Template::Error
(undefined method `name' for ["", [
  #<Administrate::Field::Number:0x00007fe6741bc170..>,
  #<Administrate::Field::String:0x00007fe6741bc120..>,
  #<Administrate::Field::Email:0x00007fe6741bc080 ..>,
  ...
  #<Administrate::Field::BelongsTo:0x00007fe6741bb..>,
  #<Administrate::Field::String:0x00007fe6741bbd60..>,
  #<Administrate::Field::String:0x00007fe6741bbcc0..>,
  #<Administrate::Field::String:0x00007fe6741bbb80..>,
]]:Array)
```

Plus a bunch of weird frontend issues, like Search input becomes blue on hover, or Datepicker not working at all. Does it use Bootstrap 5 ? and if yes, if the main app already uses Bootstrap 4.6

_Originally posted by @januszm in https://github.com/thoughtbot/administrate/issues/2518#issuecomment-1947187337_

**Comment by nickcharlton** [comment]
@januszm, I think you're hitting a few things here, one of which was a mistake by me.

* Could you describe in more detail what custom modifications you're making with the view templates?
* We don't use Bootstrap, we have our own small CSS framework in Administrate itself,
* The search input issues were probably caused by #2492 and fixed in #2512,
* How does the Datepicker fail? Just not load at all?

Could you try with current `main` and let me know what's still broken?

**Comment by januszm** [comment]
@nickcharlton  thanks for your quick reply, let me clarify this as I was already able to resolve issue 1.

First, problem with template from 0.19 that was customized, and below are diffs that solved it:

```
- ... ) if valid_action?(:edit) && show_action?(:edit, page.resource) %>
+ ... ) if accessible_action?(page.resource, :edit) %>
```
(valid_action? => accessible_action?)

```
- <% page.attributes.each do |attribute| %>
+ <% page.attributes.each do |title, attributes| %>
```

this is I believe what caused the no method error `name` for `[...]` Array, (attribute vs attributes)

Search box with weird blue background on hove (see attachment) 
<img width="367" alt="Screenshot 2024-02-16 at 14 47 53" src="https://github.com/thoughtbot/administrate/assets/864446/ede2e301-6616-4994-ba9e-4d71a3355128">


Datepicker actually WORKS but it uses white font color on white background which of course makes the text invisible and suggests that it isn't working. (see attachment)
<img width="533" alt="Screenshot 2024-02-16 at 14 48 52" src="https://github.com/thoughtbot/administrate/assets/864446/155f2c96-8553-46e0-a92c-543a5416c6e4">

**Comment by januszm** [comment]
@nickcharlton  also, the last two (visual) issues are solved on the `main` branch. I've just updated the gem and it looks good.

So the potential, future "Upgrade to v1" Guide should contain information about the need to re-generated the customized partials and re-apply added code. I think that's all.

**Comment by nickcharlton** [comment]
> So the potential, future "Upgrade to v1" Guide should contain information about the need to re-generated the customized partials and re-apply added code. I think that's all.

Alright, cool! I'll add a mention to explicitly call that out in the migration guide. It is something we started highlighting in the [CHANGELOG](https://github.com/thoughtbot/administrate/blob/main/CHANGELOG.md#0200-january-17-2024), but that's always easy to miss.

**Comment by nickcharlton** [comment]
Re: `<pre>`, can you tell if that's something that changed in the linting PR? If it was, I think we should undo that specific change as it wasn't intentional.

**Comment by januszm** [comment]
ReL `<pre>`, for a regular field it looks ok, both white-space and word-wrap attributes are set properly.
In my case the issue is with a custom field (data type) that I called PrettyJson (it's a type that I use to dump a typical jsonb column data).
It generates the following css class which is missing the necessary white-space attr `attribute-data attribute-data--pretty-json-field`

**Comment by januszm** [comment]
Any chance I can tell my custom field class to use `preserve-whitespace` CSS class on the generated element? Just like for the Field::Text class.

What I need is the same as is generated from Field::Text, so:
```html
<dd class="attribute-data attribute-data--text">
  <div class="preserve-whitespace">...
```

but instead I'm getting:
```html
<dd class="attribute-data attribute-data--pretty-json-field"><pre>...
```

**Comment by nickcharlton** [comment]
Ah, hah! Excellent. Glad to hear you figured it out.

Is that everything you were having trouble with?

**Comment by januszm** [comment]
All good now.

I'd make this section of the migrating .md file a bit more detailed, e.g.

```
As with most upgrades, if you're upgrading between versions with changes to the
templates, and if you've customised them, you may need to apply recent changes.
You can see those which changed in the [CHANGELOG][].

This applies to both modified files in `app/views/admin` and `app/views/fields` if you have your own Field classes defined. A good way is to use the same command to generate the view as for the earlier version (`rails generate administrate:views:ACTION MyModel`), noting the changes and re-applying the modifications
```

**Comment by nickcharlton** [comment]
Oh, yes, that's a great idea. I'll do that.

I'll close this now, but please open new issues if you find problems.
